version: '3.6'
services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"

    image: mysql:8.0.32
    container_name: mysql_docker
    volumes:
      - ./init:/docker-entrypoint-initdb.d
